service: mieteiru

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x


package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  whois:
    handler: bin/whois
    events:
      - http:
          path: whois/{domain}
          method: get
          cors: true
  lookupHost:
    handler: bin/lookupHost
    events:
      - http:
          path: lookupHost/{domain}
          method: get
          cors: true
  lookupMX:
    handler: bin/lookupMX
    events:
      - http:
          path: lookupMX/{domain}
          method: get
          cors: true
  lookupAddr:
    handler: bin/lookupAddr
    events:
      - http:
          path: lookupAddr/{addr}
          method: get
          cors: true
  lookupNS:
    handler: bin/lookupNS
    events:
      - http:
          path: lookupNS/{domain}
          method: get
          cors: true